version: '3'
services:
  server:
    container_name: ambar-prod-server
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - redis
      - mongo
  mongo:
    container_name: ambar-mongo
    image: 'mongo:4'
  redis:
    container_name: ambar-redis
    image: 'redis:4.0.11'
